server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/veyselkayhan/java11configserver2.git"
          default-label: main
          skip-ssl-validation: true
          username: veyselkayhan
          password: ${GIT_KEY}